"""Menambah Column Id Music And Video

Revision ID: 58c22d72cce0
Revises: 
Create Date: 2025-09-11 12:36:24.927478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c22d72cce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_public_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('audio_public_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('album_art_public_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.drop_column('album_art_public_id')
        batch_op.drop_column('audio_public_id')
        batch_op.drop_column('video_public_id')

    # ### end Alembic commands ###
